Web-Design-Match -> Web-Design
katapultman/TUESPairs pull request #12
Opened 2020-04-13 16:14 UTC by marianbitsov23

Stable web version.
Added design on the home page.
Major bug fixes.

2020-04-13 17:34 UTC, msimov02 approved these changes
LGTM!

2020-04-14 12:04 UTC, GGLozanov requested changes
Малка промяна за debug print-а, иначе LGTM.

2020-04-14 12:04 UTC, katapultman commented on Web/tues_pairs/src/components/Pages/Home/home.jsx
> +    console.log("Here");
Изтрии това.

2020-04-14 14:08 UTC, GGLozanov approved these changes
Добре, LGTM.

2020-04-14 14:08 UTC, merged