Web-Chat -> Web
katapultman/TUESPairs pull request #19
Opened 2020-04-25 16:20 UTC by martinsimov10a19

Implementation of web chat.

2020-04-25 16:23 UTC, marianbitsov23 requested changes
Защо е махнат Safeguard-а на страницата ? Така всеки ако ръчно си напише /chat ще може да гледа страницата, даже и да не се е логнал

2020-04-25 16:26 UTC, marianbitsov23 approved these changes

2020-04-25 16:27 UTC, marianbitsov23 commented
> Защо е махнат Safeguard-а на страницата ? Така всеки ако ръчно си напише /chat ще може да гледа страницата, даже и да не се е логнал

опа, просто е преместено отдолу извинявам се, LGTM !

2020-04-25 16:29 UTC, marianbitsov23 commented
Само едно нещо package-lock.json не е нужно да го комитваш то се генерира автоматично като напишеш npm install.

2020-04-25 20:06 UTC, katapultman commented on Web/tues_pairs/src/components/Pages/Home/alreadyMatched.jsx
> -            }
Това за какво е било махнато?

2020-04-26 13:06 UTC, martinsimov10a19 commented on Web/tues_pairs/src/components/Pages/Home/alreadyMatched.jsx
> -            }
Това е ако нямаме права в firestore, но поенже ние имаме права не ни е нужно.

2020-04-26 13:07 UTC, katapultman commented on Web/tues_pairs/src/components/Pages/Home/alreadyMatched.jsx
> -            }
I see.

2020-04-26 13:07 UTC, GGLozanov approved these changes
LGTM. Changes approved.

2020-04-26 13:08 UTC, merged