Web settings
katapultman/TUESPairs pull request #3
Opened 2020-03-26 19:34 UTC by marianbitsov23

Fully Working Account(Settings) page.
One remaining thing -  option for deleting profile completely.

2020-03-26 20:48 UTC, GGLozanov requested changes
Изглежда добре освен една част в home.js, където проверяваш за свързаност учител-ученик. Там if-a ти е:

`if(currentUser.isTeacher !== users[i].isTeacher && !currentUser.skippedUserIDs.includes(users[i].uid))`

А мисля, че ще е по-добре ако е като този на мобилната версия (който филтрира и хора, които са вече match-нати); т.е js имплементациата на.:

`if(currentUser.uid != user.uid && currentUser.isTeacher != user.isTeacher
            && !currentUser.skippedUserIDs.contains(user.uid) &&
            (user.matchedUserID == null || user.matchedUserID == currentUser.uid) && !user.skippedUserIDs.contains(currentUser))`

2020-03-26 21:10 UTC, marianbitsov23 reviewed
Направих промяната, но премахнах едното условие(това с id-то), защото условитеа за Teacher го overwrite-ва и така е по-оптимално.

2020-03-26 21:12 UTC, katapultman commented
> Направих промяната, но премахнах едното условие(това с id-то), защото условитеа за Teacher го overwrite-ва и така е по-оптимално.

Ясно. Изглежда добре. Ще го ъпдейтна условието и в Mobile версията. Добре хванат бъг.

2020-03-26 21:13 UTC, GGLozanov approved these changes
Changes approved.

2020-03-26 21:14 UTC, marianbitsov23 commented
> Changes approved.

_**Благодаря ти, неимуверно много!**_ 💋

2020-03-27 13:52 UTC, martinsimov10a19 commented
LGTM !

2020-03-27 21:34 UTC, merged